### ISSUE TITLE
[BUG]     :: There appears to be a bug on Line 545 of operations.py

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#214]
I'm on the up-to date version of the master branch and I'm trying to reduce a set of data that I successfully reduced with an earlier version of PYPIT.

For my .pypit file I have,

```
run ncpus 1
output overwrite True
run spectrograph lris_blue
run setup False
run calcheck false

output sorted lris_blue_setup_A

# Reduce
bias useframe overscan
arc calibrate method arclines
trace slits number 1

```
I've gone through the setup and calcheck and working on the actual reduction and I'm getting this error 

```
[BUG]     :: There appears to be a bug on Line 545 of operations.py with error:
             The 'Ei           Ek' columns have incompatible types: ['string224', 'string224', 'string192', 'string216', 'string216', 'int64', 'string192', 'string200']
             ---> please contact the authors
```
I don't even see 'operations.py' in the PYPIT/pypit directory. Anybody know what might be going on?

**Comment by rcooke-ast** [comment]
Thanks for raising the issue -- In `ardebug.py`, if you change the flag to `develop=True`, and rerun the code, could you please paste the error message that you get? This one is a bit tough to decipher as is.

**Comment by AlexaVillaume** [comment]
```
Traceback (most recent call last):
  File "/Users/alexa/anaconda/bin/run_pypit", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/alexa/PYPIT/bin/run_pypit", line 16, in <module>
    run_pypit.main(args)
  File "/Users/alexa/PYPIT/pypit/scripts/run_pypit.py", line 82, in main
    use_masters=args.use_masters, logname=logname, debug=debug)
  File "/Users/alexa/PYPIT/pypit/pypit.py", line 228, in PYPIT
    status = armlsd.ARMLSD(fitsdict)
  File "/Users/alexa/PYPIT/pypit/armlsd.py", line 150, in ARMLSD
    update = slf.MasterWaveCalib(fitsdict, sc, det)
  File "/Users/alexa/PYPIT/pypit/arsciexp.py", line 745, in MasterWaveCalib
    wv_calib = ararc.calib_with_arclines(self, det)
  File "/Users/alexa/PYPIT/pypit/ararc.py", line 554, in calib_with_arclines
    best_dict, final_fit = semi_brute(spec, aparm['lamps'], aparm['wv_cen'], aparm['disp'], fit_parm=aparm) #min_ampl=min_ampl,
  File "/Users/alexa/arclines/arclines/holy/grail.py", line 223, in semi_brute
    full_NIST = arcl_io.load_line_lists(lines, NIST=True)
  File "/Users/alexa/arclines/arclines/io.py", line 134, in load_line_lists
    line_lists = vstack(lists, join_type='exact')
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/astropy/table/operations.py", line 253, in vstack
    out = _vstack(tables, join_type, col_name_map)
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/astropy/table/operations.py", line 789, in _vstack
    out_descrs = get_descrs(arrays, col_name_map)
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/astropy/table/operations.py", line 545, in get_descrs
    .format(names[0], tme._incompat_types))
astropy.table.np_utils.TableMergeError: The 'Ei           Ek' columns have incompatible types: ['string224', 'string224', 'string192', 'string216', 'string216', 'int64', 'string192', 'string200']
```

**Comment by profxj** [comment]
This is an arclines issue.  Please raise it there.

And, I've hit it myself and have nearly fixed it (will
give it higher priority).
