### ISSUE TITLE
Masking (or not) in XSpectrum1D

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#224]
See issue #385 in linetools (https://github.com/linetools/linetools/issues/385):

On line 408 of pypit/arload.py I set masking='none', so,

`    spec = XSpectrum1D.from_file(fname, exten=exten, masking='none', **rsp_kwargs)
`
However, I still get an an error when I try to run coadd_1dspec,

```
Traceback (most recent call last):
  File "/Users/alexa/anaconda/bin/pypit_coadd_1dspec", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/alexa/PYPIT/bin/pypit_coadd_1dspec", line 11, in <module>
    coadd_1dspec.main(args)
  File "/Users/alexa/PYPIT/pypit/scripts/coadd_1dspec.py", line 101, in main
    spectra = arcoadd.load_spec(gdfiles, iextensions=extensions, extract=ex_value, flux=flux_value)
  File "/Users/alexa/PYPIT/pypit/arcoadd.py", line 518, in load_spec
    spectra = collate(spectra_list)
  File "/Users/alexa/linetools/linetools/spectra/utils.py", line 147, in collate
    maxpix = max(maxpix, spec.npix)
  File "/Users/alexa/linetools/linetools/spectra/xspectrum1d.py", line 408, in npix
    self.set_diagnostics()  # Need to re-run in case self.select changes
  File "/Users/alexa/linetools/linetools/spectra/xspectrum1d.py", line 440, in set_diagnostics
    self._wvmin = np.min(self.wavelength[gdpx])
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2356, in amin
    return amin(axis=axis, out=out)
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/astropy/units/quantity.py", line 1443, in min
    return self._wrap_function(np.min, axis, out=out, keepdims=keepdims)
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/astropy/units/quantity.py", line 1408, in _wrap_function
    value = function(self.view(np.ndarray), *args, **kwargs)
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2359, in amin
    out=out, keepdims=keepdims)
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```
Are there more things I need to change to not do any masking?

**Comment by AlexaVillaume** [comment]
Looks like the issue is not in linetools but for some reason the optimal extraction failed. Should probably go back and understand why at some point.

For now I'm going to set the boxcar option in the yaml file.

**Comment by AlexaVillaume** [comment]
(This should be added to the coadd documentation at some point)

Since the optimal extraction failed I coadded using the boxcar extraction, this is how I set that in the .yaml file,

```
'extract': 'box'
'filenames': [
              'spec1d_B225-G280_LRISb_2016Oct27T055241.fits',
              'spec1d_B225-G280_LRISb_2016Oct27T055724.fits', 
              'spec1d_B225-G280_LRISb_2016Oct27T060210.fits'
              ]
'a':
    'object': [
               'O290-S1592-D02-I0002',
               'O457-S1592-D02-I0003',
               'O626-S1592-D02-I0004'
               ]
    'outfile': 'b225_g280.hdf5'
```

**Comment by AlexaVillaume** [comment]
Masking issue is probably fixed in rebin_part4 in linetools.

**Comment by profxj** [comment]
I have eliminated all masking (I think) in PYPIT
